### ISSUE TITLE
Filter by category

### ISSUE THREAD

**Issue by filliph** [Monetarists/frontend#34]
## Core Concept
A drop-down box containing all categories should be added to the filter area. Selecting this box will display only recipes from within that category.

Possibility of using multi-select?

## Tasks
- [ ] Obtain a JSON file containing all UI / Search categories
- [ ] Load this JSON file and use its data to construct the drop-down
- [ ] Apply the filter to the recipe search

**Comment by filliph** [comment]
Added in cca4b9a841234f5d0f215708e0f3e033814e0fed
