### ISSUE TITLE
Default filters

### ISSUE THREAD

**Issue by filliph** [Monetarists/frontend#35]
## Core Concept
In the Settings modal, it should be possible to set defaults for the Profit / Sold / Category filters.

## Tasks
- [ ] Update settings modal to have input boxes for default filters
- [ ] Save these defaults in a cookie
- [ ] Parse the cookie on the Crafter page and load them into the filter boxes

**Comment by filliph** [comment]
Added a better version in b8e37491ae79edbe43048df54778563f8a8b1e6d
